version: '3.4'

services:
  AirTrafficInfo_1:
    image: airtrafficinfo
    container_name: airtrafficinfo_1
    build:
      context: ./AirTrafficInfo
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8880:80"
  Plane_1:
    image: plane
    container_name: plane_1
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8001:80"
  Plane_2:
    image: plane
    container_name: plane_2
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8002:80"
  Plane_3:
    image: plane
    container_name: plane_3
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8003:80"
  Airport_1:
    image: airport
    container_name: airport_1
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8801:80"
    command: color=#ff0000
  Airport_2:
    image: airport
    container_name: airport_2
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8802:80"
    command: color=#00ff00
  Airport_3:
    image: airport
    container_name: airport_3
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8803:80"
    command: color=#0000ff