version: '3.4'

services:
  AirTrafficInfo_1:
    image: airtrafficinfo
    container_name: airtrafficinfo_1
    build:
      context: ./AirTrafficInfo
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8880:80"
  Plane_1:
    image: plane
    container_name: plane_1
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8001:80"
    command: --name=Docker_Plane1
  Plane_2:
    image: plane
    container_name: plane_2
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8002:80"
    command: --name=Docker_Plane2
  Plane_3:
    image: plane
    container_name: plane_3
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8003:80"
    command: --name=Docker_Plane3
  Airport_1:
    image: airport
    container_name: airport_1
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8801:80"
    command: --name=Docker_Airport1 --color=#FF0000 --latitude=50 --longitude=50
  Airport_2:
    image: airport
    container_name: airport_2
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8802:80"
    command: --name=Docker_Airport2 --color=#00FF00 --latitude=30 --longitude=100
  Airport_3:
    image: airport
    container_name: airport_3
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8803:80"
    command: --name=Docker_Airport3 --color=#0000FF --latitude=10 --longitude=10